var smartcar = ''
+'<?xml version="1.0" encoding="UTF-8"?>\n'
+'<kml xmlns="http://earth.google.com/kml/2.2">\n'
+'<Document>\n'
+'	<name>smart</name>\n'
+'	<StyleMap id="msn_ylw-pushpin">\n'
+'		<Pair>\n'
+'			<key>normal</key>\n'
+'			<styleUrl>#sn_ylw-pushpin</styleUrl>\n'
+'		</Pair>\n'
+'		<Pair>\n'
+'			<key>highlight</key>\n'
+'			<styleUrl>#sh_ylw-pushpin</styleUrl>\n'
+'		</Pair>\n'
+'	</StyleMap>\n'
+'	<Style id="sn_ylw-pushpin">\n'
+'		<IconStyle>\n'
+'			<scale>1.1</scale>\n'
+'			<Icon>\n'
+'				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>\n'
+'			</Icon>\n'
+'			<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>\n'
+'		</IconStyle>\n'
+'	</Style>\n'
+'	<Style id="sh_ylw-pushpin">\n'
+'		<IconStyle>\n'
+'			<scale>1.3</scale>\n'
+'			<Icon>\n'
+'				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>\n'
+'			</Icon>\n'
+'			<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>\n'
+'		</IconStyle>\n'
+'	</Style>\n'
+'	<Placemark>\n'
+'		<name>smart</name>\n'
+'		<LookAt>\n'
+'			<longitude>-57.34469373397084</longitude>\n'
+'			<latitude>29.50804036118333</latitude>\n'
+'			<altitude>0</altitude>\n'
+'			<range>7</range>\n'
+'			<tilt>0</tilt>\n'
+'			<heading>0</heading>\n'
+'		</LookAt>\n'
+'		<styleUrl>#msn_ylw-pushpin</styleUrl>\n'
+'		<Model id="model_1">\n'
+'			<Location>\n'
+'				<longitude>-57.34470504016051</longitude>\n'
+'				<latitude>29.5080300577348</latitude>\n'
+'				<altitude>0</altitude>\n'
+'			</Location>\n'
+'			<Orientation>\n'
+'				<heading>0</heading>\n'
+'				<tilt>0</tilt>\n'
+'				<roll>0</roll>\n'
+'			</Orientation>\n'
+'			<Scale>\n'
+'				<x>2.583019100311845</x>\n'
+'				<y>2.583018851523333</y>\n'
+'				<z>2.583018975917589</z>\n'
+'			</Scale>\n'
+'			<Link>\n'
+'				<href>test/smart.dae</href>\n'
+'			</Link>\n'
+'			<ResourceMap>\n'
+'			</ResourceMap>\n'
+'		</Model>\n'
+'	</Placemark>\n'
+'</Document>\n'
+'</kml>';
